# springboot 整合mybatis
# 数据库的信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置文件的绑定和别名
mybatis:
  mapper-locations: classpath:mapper/*.xml # mapper映射文件路径
  type-aliases-package: com.qin.springboot01.pojo   # 配置哪个包下的类有默认的别名


student:
  lastName: sangeng
  age:  18
  boos: true
  birthday: 1998/10/30
  # 第一种写法
  maps:
    sangeng: caotang
    xuexi: bizhan
  # 第二种行内写法
  maps2: {sangeng: caotang,xuexi: bizhan}
  list:
    - name: 小黑
      age: 3
    - name: 小黄
      age: 4
    - {name: 小王,age: 12}
  dog:
    name: 小黑
    age: 18
  arr:
    - sangeng
    - caotang
  # 数组的行内写法
  arr2: [sangeng,caotang]
  dogMap:
    sangeng: {name: 小白,age: 9}
    caotang:
      name: 小黑
      age: 6



